### ISSUE TITLE
Geolocalisation

### ISSUE THREAD

**Issue by Desiderius77** [ALXRSS/WebRTC-Conf#34] opened 2015-03-06 15:03 UTC
On the demo page hosted at  http://visio.gexsoft.com , I was surprised to see that
when I click on the Geoloc button, a map appears immediatly and I do not see a popup windows asking me wheter I want to be localized or not ?

People explicitly asked me yesterday if the product works normally if the user does not want to be localized.

**Comment by micbuffa** [comment] 2015-03-06 15:50
I told you, it's a protocol problem. For me : chat + geoloc + p2p file transfert does not work, and I've got this on the console : http://i.imgur.com/yeedSOl.jpg

**Comment by j-mulenet** [comment] 2015-03-06 15:54
We think that it's a problem with the adress assigned in the socket client, Client try to connect with socket.io but it can't because the adress was assigned to "localhost".
We will fix that soon.

**Comment by micbuffa** [comment] 2015-03-06 19:55
Yes, it's a good practice not to do var socket = io.connect('http://'+location.hostname + ':3000');

But instead io.connect(); // Means -> connect to the server that served the page !

**Comment by polskataga** [comment] 2015-03-10 13:41
Yes, the product works normally if the user does not want to be localized. The user has the choice.

**Comment by micbuffa** [comment] 2015-03-11 06:33
I updated the version that is online with yersterday's last version of one-to-many-current.....

I have a strange error in the console relative to socket.io-stream, "undefined symbol", when I click to see the error in the js file, the js file only contains "welcome to socket.io-stream". I added socket.io streams to the package.json file + did a npm install. maybe I broke something ?

Anyway, the app at visio.gexsoft.com seems to work pretty well, except the geolocation thats eems to be broken. When I started the app as a second participant, it blocked for 30s "wating for ajax.googleapis.com" in the browser's status zone, then the room I created with the first participant appeared, it took 30s to see the room on screen. Is it normal ?

**Comment by micbuffa** [comment] 2015-03-11 06:36
Errors I've got : <a href="http://imgur.com/WMclR94"><img src="http://i.imgur.com/WMclR94.jpg" title="source: imgur.com" /></a>

**Comment by micbuffa** [comment] 2015-03-11 06:37
Also, what is the second icon on the top left, the finger with a line ? It does nothing for me ?
Do you want me to put online other versions ? Many to many ? etc ?

**Comment by polskataga** [comment] 2015-03-11 07:55
Hi, the app at visio.gexsoft.com seems to work for us too. We cannot try to test the geolocation now because of the restriction we have at work, however we tested this point yesterday with success. What is exactly the problem you have with the geolocalisation ?

Futhermore, When we want to join a room as a second participant, it takes only a few seconds for the room created to appear (after the two pop-up referring respectively to the geolocalisation and the webcam). Do you think it is a question of speed internet connection ?

**Comment by polskataga** [comment] 2015-03-11 08:00
Otherwise, the second icon on the left you are talking about allows you to "drag and drop" the videos of the different participants. When you click on this button, all the videos displayed become draggable.

Yes why not, you can try to put online many2many-current-version.

**Comment by Desiderius77** [comment] 2015-03-11 08:35
The new version at http://visio.gexsoft.com seems to work well !

Geoloc is working and is fast ! Chat also work ! and the list of participants is correct

@polskataga I have tried the seconnd icon to drag vidéos : wonderful !
But how can I get back ? That is : I do not want to drag the videos anymore !
I have to try to click again on the icon but without successs

**Comment by Desiderius77** [comment] 2015-03-11 08:37
For Geolocalisation I use the Mozilla Location Service on my laptop

**Comment by polskataga** [comment] 2015-03-11 08:51
Indeed @Desiderius77, we have to work on it. There is no way to disable the Drag'n'drop for the moment. Maybe we would disable the function on a second click on the same button or another button ...

**Comment by j-mulenet** [comment] 2015-03-11 08:52
@micbuffa For the problem with socket.io.stream, it's a error that we forget to delete, but it does not prevent the functioning of send file.

For send file one to one, we need used the socket for send file, because we have problems to make the correspondence between users in peer to peer and user socket.

Concernly the problem of maps, the position was send when the user click on the button of geolocalisation. There are a bug with google chrome, it send onetime the position at the first connection to server and at other connection it don't ask if the user want to be locate. User must delete anytime the choice after connection. We check yet for fix this problem.
For Firefox it's ok because it ask always if the user want to be locate or not every time when it connects.

**Comment by Desiderius77** [comment] 2015-03-11 08:57
@polskataga Removing the "draggable= true" attribute on the video tag is not sufficent ?

An error in the HTML5 spec or in the Firefox implementation ?

**Comment by polskataga** [comment] 2015-03-11 09:09
Yes @Desiderius77, it can be done removing the "draggable= true" attribute on the video tag but we did not know if we had to create a second eventListener on the same event "click" on the same button OR create another button only to disable the function.

Maybe, we have to create a boolean to check if the videos have the attribute "draggable= true".

**Comment by Desiderius77** [comment] 2015-03-11 09:22
Yes you can check if the video has the attribute "draggable= true" and you change the icon according to the status : one icon for dragging enable and anotherv one for dragging disabled

**Comment by micbuffa** [comment] 2015-03-11 09:24
Ok, geoloc is not working for me on Google Chrome while all my geoloc examples on jsbin.com works well. Here is a picture of what I see when I try on my machine with two tabs and two participants :+1: 
<a href="http://imgur.com/p9Az2tI"><img src="http://i.imgur.com/p9Az2tI.jpg" title="source: imgur.com" /></a>

**Comment by micbuffa** [comment] 2015-03-11 09:26
Same error with firefox :+1: 
<a href="http://imgur.com/Mubu5hk"><img src="http://i.imgur.com/Mubu5hk.jpg" title="source: imgur.com" /></a>

**Comment by micbuffa** [comment] 2015-03-11 09:27
As you can see the map does not show a correct position. And it's not a network problem, as I told you all my examples of geoloc work well, same machine, same browser, same wifi.

**Comment by Desiderius77** [comment] 2015-03-11 09:30
@micbuffa Strange ! I have just relaunched the page to check : Geoloc is working fine
and get the right position ( Firefox ) ; I will check with Chromium on Linux

**Comment by Desiderius77** [comment] 2015-03-11 09:31
Same with Chromium : position acquired in 5 seconds and right !

**Comment by micbuffa** [comment] 2015-03-11 09:31
I'm on a Mac. Also, a suggestion, I don't know if you've done it or if you have time to do it:
Click on the name of a participant and center the map on him. This is really cool.

**Comment by Desiderius77** [comment] 2015-03-11 09:34
No I will try !

here is the snapshot of my firefox window 
![webrct](https://cloud.githubusercontent.com/assets/3873415/6593593/30c66d18-c7da-11e4-9ca4-1783feb51b49.jpg)

**Comment by micbuffa** [comment] 2015-03-11 09:38
Hmmm.... you connected only one user, ot there must be at least twice ? Did you try on two tabs same machine ?

**Comment by Desiderius77** [comment] 2015-03-11 09:40
I only connecteed myself in the room ?

I will try with two tabs

**Comment by micbuffa** [comment] 2015-03-11 09:43
It does not work for me, I tried several times, on ff, opera, chrome...
ALso, on your screenshot, it would be good to be able to see in a tooltip the name of the person, when we put the mouse on the small blue man's icon... (maybe you've done that, but as geoloc does not work for me...)

**Comment by micbuffa** [comment] 2015-03-11 09:44
And I've got also lots of warning/errors in the console
in socket.io, in jquery etc
I will take screenshots

**Comment by micbuffa** [comment] 2015-03-11 09:46
<a href="http://imgur.com/z7kZP0x"><img src="http://i.imgur.com/z7kZP0x.jpg" title="source: imgur.com" /></a>

**Comment by Desiderius77** [comment] 2015-03-11 09:46
Sorry for you Michel !

I have tried with 2 tabs and everything works well ( Firefox Linux ) ; Effectively when I click on the blue icon on the map , I get my pesudo !

**Comment by micbuffa** [comment] 2015-03-11 09:48
Ok, I think the problem is somewhere else... give a look at the errors in my console, check if you've got the same. I was alone before even entering a room when I took the screenshot. After authorizing geoloc + entering nickname.

Did you see my comment about centering map when cliking on a member's name. This is a nice feature to implement if you have time.

**Comment by j-mulenet** [comment] 2015-03-11 09:49
The problem that micbuffa meeting with maps was a random problem we know with some people, we will fix it soon. We will based on example of jsbin.
We will add the functionnality for centering map

**Comment by micbuffa** [comment] 2015-03-11 09:52
Ok, no stress, I'm in a boring meeting so I work a little testing your project :-)

**Comment by j-mulenet** [comment] 2015-03-14 14:27
I send a pull request that fix the problem of send of geoposition.
It's resolved.

**Closed as completed by j-mulenet** 2015-03-14 14:27 UTC
